import pyganim

bolt_animation = pyganim.PygAnimation([('Resource/bolt_strike_0001.png', 0.1),
                                 ('Resource/bolt_strike_0002.png', 0.1),
                                 ('Resource/bolt_strike_0003.png', 0.1),
                                 ('Resource/bolt_strike_0004.png', 0.1),
                                 ('Resource/bolt_strike_0005.png', 0.1),
                                 ('Resource/bolt_strike_0006.png', 0.1),
                                 ('Resource/bolt_strike_0007.png', 0.1),
                                 ('Resource/bolt_strike_0008.png', 0.1),
                                 ('Resource/bolt_strike_0009.png', 0.1),
                                 ('Resource/bolt_strike_0010.png', 0.1)])

flame_animation = pyganim.PygAnimation([('Resource/flame_a_0001.png', 0.1),
                                 ('Resource/flame_a_0002.png', 0.1),
                                 ('Resource/flame_a_0003.png', 0.1),
                                 ('Resource/flame_a_0004.png', 0.1),
                                 ('Resource/flame_a_0005.png', 0.1),
                                 ('Resource/flame_a_0006.png', 0.1)])

smoke_animation = pyganim.PygAnimation([('Resource/smoke_puff_0001.png', 0.1),
                                 ('Resource/smoke_puff_0002.png', 0.1),
                                 ('Resource/smoke_puff_0003.png', 0.1),
                                 ('Resource/smoke_puff_0004.png', 0.1),
                                 ('Resource/smoke_puff_0005.png', 0.1),
                                 ('Resource/smoke_puff_0006.png', 0.1),
                                 ('Resource/smoke_puff_0007.png', 0.1),
                                 ('Resource/smoke_puff_0008.png', 0.1),
                                 ('Resource/smoke_puff_0009.png', 0.1),
                                 ('Resource/smoke_puff_0010.png', 0.1)])

Attack1Framerate = 0.02
attack_animation_1 = pyganim.PygAnimation([('Resource/Attack/attack (1).png', Attack1Framerate),
                                 ('Resource/Attack/attack (2).png', Attack1Framerate),
                                 ('Resource/Attack/attack (3).png', Attack1Framerate),
                                 ('Resource/Attack/attack (4).png', Attack1Framerate),
                                 ('Resource/Attack/attack (5).png', Attack1Framerate),
                                 ('Resource/Attack/attack (6).png', Attack1Framerate),
                                 ('Resource/Attack/attack (7).png', Attack1Framerate),
                                 ('Resource/Attack/attack (8).png', Attack1Framerate),
                                 ('Resource/Attack/attack (9).png', Attack1Framerate),
                                 ('Resource/Attack/attack (10).png', Attack1Framerate),
                                 ('Resource/Attack/attack (11).png', Attack1Framerate),
                                 ('Resource/Attack/attack (12).png', Attack1Framerate),
                                 ('Resource/Attack/attack (13).png', Attack1Framerate),
                                 ('Resource/Attack/attack (14).png', Attack1Framerate),
                                 ('Resource/Attack/attack (15).png', Attack1Framerate),
                                 ('Resource/Attack/attack (16).png', Attack1Framerate),
                                 ('Resource/Attack/attack (17).png', Attack1Framerate),
                                 ('Resource/Attack/attack (18).png', Attack1Framerate),
                                 ('Resource/Attack/attack (19).png', Attack1Framerate),
                                 ('Resource/Attack/attack (20).png', Attack1Framerate),
                                 ('Resource/Attack/attack (21).png', Attack1Framerate),
                                 ('Resource/Attack/attack (22).png', Attack1Framerate),
                                 ('Resource/Attack/attack (23).png', Attack1Framerate),
                                 ('Resource/Attack/attack (24).png', Attack1Framerate),
                                 ('Resource/Attack/attack (25).png', Attack1Framerate),
                                 ('Resource/Attack/attack (26).png', Attack1Framerate),
                                 ('Resource/Attack/attack (27).png', Attack1Framerate),
                                 ('Resource/Attack/attack (28).png', Attack1Framerate),
                                 ('Resource/Attack/attack (29).png', Attack1Framerate),
                                 ('Resource/Attack/attack (30).png', Attack1Framerate),
                                 ('Resource/Attack/attack (31).png', Attack1Framerate),
                                 ('Resource/Attack/attack (32).png', Attack1Framerate),
                                 ('Resource/Attack/attack (33).png', Attack1Framerate),
                                 ('Resource/Attack/attack (34).png', Attack1Framerate),
                                 ('Resource/Attack/attack (35).png', Attack1Framerate),
                                 ('Resource/Attack/attack (36).png', Attack1Framerate),
                                 ('Resource/Attack/attack (37).png', Attack1Framerate),
                                 ('Resource/Attack/attack (38).png', Attack1Framerate),
                                 ('Resource/Attack/attack (39).png', Attack1Framerate),
                                 ('Resource/Attack/attack (40).png', Attack1Framerate),
                                 ('Resource/Attack/attack (41).png', Attack1Framerate),
                                 ('Resource/Attack/attack (42).png', Attack1Framerate),
                                 ('Resource/Attack/attack (43).png', Attack1Framerate),
                                 ('Resource/Attack/attack (44).png', Attack1Framerate),
                                 ('Resource/Attack/attack (45).png', Attack1Framerate),
                                 ('Resource/Attack/attack (46).png', Attack1Framerate),
                                 ('Resource/Attack/attack (47).png', Attack1Framerate),
                                 ('Resource/Attack/attack (48).png', Attack1Framerate),
                                 ('Resource/Attack/attack (49).png', Attack1Framerate),
                                 ('Resource/Attack/attack (50).png', Attack1Framerate),
                                 ('Resource/Attack/attack (51).png', Attack1Framerate),
                                 ('Resource/Attack/attack (52).png', Attack1Framerate),
                                 ('Resource/Attack/attack (53).png', Attack1Framerate),
                                 ('Resource/Attack/attack (54).png', Attack1Framerate),
                                 ('Resource/Attack/attack (55).png', Attack1Framerate),
                                 ('Resource/Attack/attack (56).png', Attack1Framerate),
                                 ('Resource/Attack/attack (57).png', Attack1Framerate),
                                 ('Resource/Attack/attack (58).png', Attack1Framerate),
                                 ('Resource/Attack/attack (59).png', Attack1Framerate),
                                 ('Resource/Attack/attack (60).png', Attack1Framerate),
                                 ('Resource/Attack/attack (61).png', Attack1Framerate),
                                 ('Resource/Attack/attack (62).png', Attack1Framerate),
                                 ('Resource/Attack/attack (63).png', Attack1Framerate)])

ExplosionFramerate = 0.025
explosion_animation = pyganim.PygAnimation([('Resource/Explosion/explosion1_0002.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0003.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0004.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0005.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0006.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0007.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0008.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0009.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0010.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0011.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0012.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0013.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0014.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0015.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0016.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0017.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0018.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0019.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0020.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0021.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0022.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0023.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0024.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0025.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0026.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0027.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0028.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0029.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0030.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0031.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0032.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0033.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0034.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0035.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0036.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0037.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0038.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0039.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0040.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0041.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0042.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0043.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0044.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0045.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0046.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0047.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0048.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0049.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0050.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0051.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0052.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0053.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0054.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0055.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0056.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0057.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0058.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0059.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0060.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0061.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0062.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0063.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0064.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0065.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0066.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0067.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0068.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0069.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0070.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0071.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0072.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0073.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0074.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0075.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0076.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0077.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0078.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0079.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0080.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0081.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0082.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0083.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0084.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0085.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0086.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0087.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0088.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0089.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0090.png', ExplosionFramerate)])


def getBoltanim():
    return bolt_animation.getCopy()
    
def getFlameanim():
    return flame_animation.getCopy()
    
def getSmokeanim():
    return smoke_animation.getCopy()

def getExplosionanim():
    return explosion_animation.getCopy()

def getAttackanim1():
    return attack_animation_1.getCopy()