import pyganim

bolt_animation = pyganim.PygAnimation([('Resource/bolt_strike_0001.png', 0.1),
                                 ('Resource/bolt_strike_0002.png', 0.1),
                                 ('Resource/bolt_strike_0003.png', 0.1),
                                 ('Resource/bolt_strike_0004.png', 0.1),
                                 ('Resource/bolt_strike_0005.png', 0.1),
                                 ('Resource/bolt_strike_0006.png', 0.1),
                                 ('Resource/bolt_strike_0007.png', 0.1),
                                 ('Resource/bolt_strike_0008.png', 0.1),
                                 ('Resource/bolt_strike_0009.png', 0.1),
                                 ('Resource/bolt_strike_0010.png', 0.1)])

flame_animation = pyganim.PygAnimation([('Resource/flame_a_0001.png', 0.1),
                                 ('Resource/flame_a_0002.png', 0.1),
                                 ('Resource/flame_a_0003.png', 0.1),
                                 ('Resource/flame_a_0004.png', 0.1),
                                 ('Resource/flame_a_0005.png', 0.1),
                                 ('Resource/flame_a_0006.png', 0.1)])

smoke_animation = pyganim.PygAnimation([('Resource/smoke_puff_0001.png', 0.1),
                                 ('Resource/smoke_puff_0002.png', 0.1),
                                 ('Resource/smoke_puff_0003.png', 0.1),
                                 ('Resource/smoke_puff_0004.png', 0.1),
                                 ('Resource/smoke_puff_0005.png', 0.1),
                                 ('Resource/smoke_puff_0006.png', 0.1),
                                 ('Resource/smoke_puff_0007.png', 0.1),
                                 ('Resource/smoke_puff_0008.png', 0.1),
                                 ('Resource/smoke_puff_0009.png', 0.1),
                                 ('Resource/smoke_puff_0010.png', 0.1)])

Attack1Framerate = 0.02
attack_animation_1 = pyganim.PygAnimation([('Resource/Attack/attack (1).png', Attack1Framerate),
                                 ('Resource/Attack/attack (2).png', Attack1Framerate),
                                 ('Resource/Attack/attack (3).png', Attack1Framerate),
                                 ('Resource/Attack/attack (4).png', Attack1Framerate),
                                 ('Resource/Attack/attack (5).png', Attack1Framerate),
                                 ('Resource/Attack/attack (6).png', Attack1Framerate),
                                 ('Resource/Attack/attack (7).png', Attack1Framerate),
                                 ('Resource/Attack/attack (8).png', Attack1Framerate),
                                 ('Resource/Attack/attack (9).png', Attack1Framerate),
                                 ('Resource/Attack/attack (10).png', Attack1Framerate),
                                 ('Resource/Attack/attack (11).png', Attack1Framerate),
                                 ('Resource/Attack/attack (12).png', Attack1Framerate),
                                 ('Resource/Attack/attack (13).png', Attack1Framerate),
                                 ('Resource/Attack/attack (14).png', Attack1Framerate),
                                 ('Resource/Attack/attack (15).png', Attack1Framerate),
                                 ('Resource/Attack/attack (16).png', Attack1Framerate),
                                 ('Resource/Attack/attack (17).png', Attack1Framerate),
                                 ('Resource/Attack/attack (18).png', Attack1Framerate),
                                 ('Resource/Attack/attack (19).png', Attack1Framerate),
                                 ('Resource/Attack/attack (20).png', Attack1Framerate),
                                 ('Resource/Attack/attack (21).png', Attack1Framerate),
                                 ('Resource/Attack/attack (22).png', Attack1Framerate),
                                 ('Resource/Attack/attack (23).png', Attack1Framerate),
                                 ('Resource/Attack/attack (24).png', Attack1Framerate),
                                 ('Resource/Attack/attack (25).png', Attack1Framerate),
                                 ('Resource/Attack/attack (26).png', Attack1Framerate),
                                 ('Resource/Attack/attack (27).png', Attack1Framerate),
                                 ('Resource/Attack/attack (28).png', Attack1Framerate),
                                 ('Resource/Attack/attack (29).png', Attack1Framerate),
                                 ('Resource/Attack/attack (30).png', Attack1Framerate),
                                 ('Resource/Attack/attack (31).png', Attack1Framerate),
                                 ('Resource/Attack/attack (32).png', Attack1Framerate),
                                 ('Resource/Attack/attack (33).png', Attack1Framerate),
                                 ('Resource/Attack/attack (34).png', Attack1Framerate),
                                 ('Resource/Attack/attack (35).png', Attack1Framerate),
                                 ('Resource/Attack/attack (36).png', Attack1Framerate),
                                 ('Resource/Attack/attack (37).png', Attack1Framerate),
                                 ('Resource/Attack/attack (38).png', Attack1Framerate),
                                 ('Resource/Attack/attack (39).png', Attack1Framerate),
                                 ('Resource/Attack/attack (40).png', Attack1Framerate),
                                 ('Resource/Attack/attack (41).png', Attack1Framerate),
                                 ('Resource/Attack/attack (42).png', Attack1Framerate),
                                 ('Resource/Attack/attack (43).png', Attack1Framerate),
                                 ('Resource/Attack/attack (44).png', Attack1Framerate),
                                 ('Resource/Attack/attack (45).png', Attack1Framerate),
                                 ('Resource/Attack/attack (46).png', Attack1Framerate),
                                 ('Resource/Attack/attack (47).png', Attack1Framerate),
                                 ('Resource/Attack/attack (48).png', Attack1Framerate),
                                 ('Resource/Attack/attack (49).png', Attack1Framerate),
                                 ('Resource/Attack/attack (50).png', Attack1Framerate),
                                 ('Resource/Attack/attack (51).png', Attack1Framerate),
                                 ('Resource/Attack/attack (52).png', Attack1Framerate),
                                 ('Resource/Attack/attack (53).png', Attack1Framerate),
                                 ('Resource/Attack/attack (54).png', Attack1Framerate),
                                 ('Resource/Attack/attack (55).png', Attack1Framerate),
                                 ('Resource/Attack/attack (56).png', Attack1Framerate),
                                 ('Resource/Attack/attack (57).png', Attack1Framerate),
                                 ('Resource/Attack/attack (58).png', Attack1Framerate),
                                 ('Resource/Attack/attack (59).png', Attack1Framerate),
                                 ('Resource/Attack/attack (60).png', Attack1Framerate),
                                 ('Resource/Attack/attack (61).png', Attack1Framerate),
                                 ('Resource/Attack/attack (62).png', Attack1Framerate),
                                 ('Resource/Attack/attack (63).png', Attack1Framerate)])

gengarFramerate = 0.03
gengarAnimation = pyganim.PygAnimation([('Resource/gengar/gengar (1).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (2).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (3).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (4).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (5).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (6).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (7).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (8).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (9).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (10).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (11).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (12).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (13).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (14).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (15).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (16).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (17).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (18).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (19).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (20).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (21).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (22).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (23).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (24).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (25).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (26).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (27).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (28).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (29).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (30).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (31).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (32).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (33).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (34).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (35).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (36).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (37).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (38).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (39).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (40).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (41).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (42).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (43).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (44).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (45).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (46).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (47).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (48).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (49).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (50).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (51).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (52).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (53).gif', gengarFramerate),
                                 ('Resource/gengar/gengar (54).gif', gengarFramerate)])


psyduckFramerate = 0.03
psyduckAnimation = pyganim.PygAnimation([('Resource/psyduck/psyduck (1).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (2).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (3).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (4).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (5).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (6).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (7).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (8).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (9).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (10).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (11).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (12).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (13).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (14).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (15).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (16).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (17).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (18).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (19).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (20).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (21).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (22).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (23).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (24).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (25).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (26).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (27).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (28).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (29).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (30).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (31).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (32).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (33).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (34).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (35).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (36).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (37).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (38).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (39).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (40).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (41).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (42).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (43).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (44).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (45).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (46).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (47).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (48).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (49).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (50).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (51).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (52).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (53).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (54).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (55).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (56).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (57).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (58).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (59).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (60).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (61).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (62).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (63).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (64).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (65).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (66).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (67).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (68).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (69).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (70).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (71).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (72).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (73).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (74).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (75).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (76).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (77).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (78).gif', psyduckFramerate),
                                 ('Resource/psyduck/psyduck (79).gif', psyduckFramerate)])

dusknoirFramerate = 0.02
dusknoirAnimation = pyganim.PygAnimation([('Resource/dusknoir/dusknoir (1).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (2).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (3).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (4).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (5).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (6).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (7).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (8).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (9).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (10).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (11).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (12).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (13).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (14).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (15).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (16).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (17).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (18).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (19).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (20).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (21).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (22).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (23).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (24).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (25).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (26).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (27).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (28).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (29).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (30).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (31).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (32).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (33).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (34).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (35).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (36).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (37).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (38).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (39).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (40).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (41).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (42).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (43).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (44).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (45).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (46).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (47).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (48).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (49).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (50).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (51).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (52).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (53).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (54).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (55).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (56).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (57).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (58).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (59).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (60).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (61).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (62).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (63).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (64).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (65).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (66).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (67).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (68).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (69).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (70).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (71).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (72).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (73).gif', dusknoirFramerate),
                                 ('Resource/dusknoir/dusknoir (74).gif', dusknoirFramerate)])


ExplosionFramerate = 0.025
explosion_animation = pyganim.PygAnimation([('Resource/Explosion/explosion1_0002.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0003.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0004.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0005.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0006.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0007.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0008.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0009.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0010.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0011.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0012.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0013.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0014.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0015.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0016.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0017.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0018.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0019.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0020.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0021.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0022.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0023.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0024.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0025.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0026.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0027.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0028.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0029.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0030.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0031.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0032.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0033.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0034.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0035.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0036.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0037.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0038.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0039.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0040.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0041.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0042.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0043.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0044.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0045.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0046.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0047.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0048.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0049.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0050.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0051.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0052.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0053.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0054.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0055.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0056.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0057.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0058.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0059.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0060.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0061.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0062.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0063.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0064.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0065.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0066.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0067.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0068.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0069.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0070.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0071.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0072.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0073.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0074.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0075.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0076.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0077.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0078.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0079.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0080.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0081.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0082.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0083.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0084.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0085.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0086.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0087.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0088.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0089.png', ExplosionFramerate),
                                 ('Resource/Explosion/explosion1_0090.png', ExplosionFramerate)])


def getBoltanim():
    return bolt_animation.getCopy()
    
def getFlameanim():
    return flame_animation.getCopy()
    
def getSmokeanim():
    return smoke_animation.getCopy()

def getExplosionanim():
    return explosion_animation.getCopy()

def getAttackanim1():
    return attack_animation_1.getCopy()

def getGengaranim():
    return gengarAnimation.getCopy()

def getPsyduckanim():
    return psyduckAnimation.getCopy()

def getDusknoiranim():
    return dusknoirAnimation.getCopy()